#ifndef CONSTANTS_H
#define CONSTANTS_H

#define AUDIO_BGMS 41
#define AUDIO_SOUNDS 86
#define AUDIO_SOUND_CHANNELS 6
#define BG_TRANSPARENT_COLOR 48
#define FILE_CMPHEADER_SIZE 16
#define FILE_ULONG_SIZE 4
#define FILE_USHORT_SIZE 2
#define FLIP_MASK 3
#define FRAME_DURATIONS 3
#define FRAMES_PER_SECOND 60
#define HFLIP 1
#define HVFLIP 3
#define NOFLIP 0
#define PALETTE_LINES_MAX 4
#define PLANE_A_HI 0
#define PLANE_A_LO 1
#define PLANE_B 2
#define PLANES_MAX 8
#define PRIORITY_MASK 0x8000
#define ROTATE_MASK 7
#define SCREEN_BPP 8
#define SCREEN_HEIGHT_PX 224
#define SCREEN_WIDTH_PX 400
#define SCREEN_WIDTH_TILES 50
#define SPRITE_BITMAPS_MAX 700
#define SPRITE_TRANSPARENT_COLOR 0xFF
#define SPRITES_MAX 80
#define PLANE_WIDTH_PX 512
#define PLANE_WIDTH_TILES 64
#define PLANE_HEIGHT_PX 256
#define PLANE_HEIGHT_TILES 32
#define SPECIAL_STAGE_FRAMES_PER_SECOND 20
#define STAMP_BITMAPS_MAX 2048
#define STAMP_MAP_HEIGHT 128
#define STAMP_MAP_WIDTH 128
#define STAMP_LENGTH 32
#define STAMP_VERSIONS 8
#define SZDD_DICTIONARY_SIZE 4096
#define TILE_BITMAPS_MAX 4096
#define TILE_CHANGE_BITMAPS_MAX 2048
#define TILE_LENGTH 8
#define TILE_VERSIONS 4
#define VFLIP 2
#define WATER_PALETTE_OFFSET 64

#endif
