#ifndef GAMEMODE_H
#define GAMEMODE_H

typedef enum gamemode {
  GAMEMODE_NONE = 0,
  GAMEMODE_NEW_GAME = 1,
  GAMEMODE_CONTINUE = 2,
  GAMEMODE_TIME_ATTACK = 3,
  GAMEMODE_SAVED_GAMES = 4,
  GAMEMODE_PLAY_MUSIC = 5,
  GAMEMODE_VISUAL_MODE = 6,
  GAMEMODE_ATTRACT_MODE = 7,
  GAMEMODE_SOUND_TEST = 13,
  GAMEMODE_STAGE_SELECT = 14,
  GAMEMODE_BEST_TIMES = 20,
  GAMEMODE_OPTIONS = 22,
  GAMEMODE_EXIT = 21
}
gamemode;

#endif
