#ifndef PSPBUTTON_H
#define PSPBUTTON_H

typedef enum psp_button {
  PSP_BUTTON_TRIANGLE = 0,
  PSP_BUTTON_CIRCLE = 1,
  PSP_BUTTON_CROSS = 2,
  PSP_BUTTON_SQUARE = 3,
  PSP_BUTTON_L = 4,
  PSP_BUTTON_R = 5,
  PSP_BUTTON_DOWN = 6,
  PSP_BUTTON_LEFT = 7,
  PSP_BUTTON_UP = 8,
  PSP_BUTTON_RIGHT = 9,
  PSP_BUTTON_SELECT = 10,
  PSP_BUTTON_START = 11,
  PSP_BUTTON_HOME = 12,
  PSP_BUTTON_HOLD = 13
}
psp_button;

#endif
