void flagwkclr(void);
void actsetchk(void);
void actsetinit(void);
void actset(void);
int tm_setchk(unsigned char cnt, unsigned short* pIndex);
int actnoset(unsigned char cnt, unsigned short* pIndex);
int actwkchk(sprite_status** ppActwk);
int actwkchk2(sprite_status* pActwk, sprite_status** ppNewActwk);
int frameout_s(sprite_status* pActwk);
int frameout_s00(sprite_status* pActwk, short xposi);
int frameout_s0(sprite_status* pActwk);
