void block(sprite_status* pActwk);
void block_init(sprite_status* pActwk);
void block_move(sprite_status* pActwk);
void block_move2(sprite_status* pActwk);
void block_move3(sprite_status* pActwk);
void block_move4(sprite_status* pActwk);
void block_move5(sprite_status* pActwk);
void block_move6(sprite_status* pActwk);
void block_ride(sprite_status* pActwk);
void ride_on_chk_b(sprite_status* pActwk, sprite_status* pPlaywk);
