unsigned int swap(int lSrc);
short dircolm(sprite_status* pActwk, char* cpDirec);
short dircol(sprite_status* pActwk, char* cpDirec);
short dircol2(sprite_status* pActwk, char* cpDirec);
short dircol_d(sprite_status* pActwk, short* ipD0, short* ipD1, short* ipD3);
short dircol_d3(sprite_status* pActwk, short iXposi, short iYposi);
short dircol_r(sprite_status* pActwk, short* ipD0, short* ipD1, short* ipD3);
short dircol_r2(sprite_status* pActwk);
short dircol_r3(sprite_status* pActwk, short iXposi, short iYposi);
short dircol_l(sprite_status* pActwk, short* ipD0, short* ipD1, short* ipD3);
short dircol_l2(sprite_status* pActwk);
short dircol_l3(sprite_status* pActwk, short iXposi, short iYposi);
short dircol_u(sprite_status* pActwk, short* ipD0, short* ipD1, short* ipD3);
short dircol_u2(sprite_status* pActwk);
short dircol_u3(sprite_status* pActwk, short iXposi, short iYposi);
short emycol_u(sprite_status* pActwk);
short emycol_d(sprite_status* pActwk);
short emycol_d2(sprite_status* pActwk, short iXposi);
short emycol_d3(sprite_status* pActwk, short iXposi, short iYposi);
short emycol_l(sprite_status* pActwk, unsigned char sprhs);
short emycol_l3(sprite_status* pActwk, short iXposi, short iYposi);
short emycol_r(sprite_status* pActwk, unsigned char sprhs);
short emycol_r3(sprite_status* pActwk, short iXposi, short iYposi);
short dircolchk(short* ipD0, short* ipD1, short* ipD3, char* cpDirec);
short dircolchk1(char cDirec);
