#include "TYPES.h"

extern unsigned char ta_flag;
extern unsigned char clrspflg_save;
extern unsigned char flagworkcnt;
extern unsigned char flagworkcnt2;
extern unsigned char play_status;
extern unsigned char pl_suu;
extern unsigned char main_play;
extern short pl_air;
extern unsigned char pltimeover_f;
extern unsigned char plring_f2;
extern unsigned char pl_suu_f;
extern unsigned char plring_f;
extern unsigned char pltime_f;
extern unsigned char plscore_f;
extern short plring;
extern int plscore;
extern unsigned char play_start;
extern unsigned char start_flag;
extern unsigned char plpower_b;
extern unsigned char plpower_m;
extern unsigned char plpower_s;
extern unsigned char plpower_a;
extern unsigned char plflag;
extern unsigned char plflag_s;
extern short plxposi_s;
extern short plyposi_s;
extern short plring_s;
extern int pltime_s;
extern unsigned char time_flag;
extern unsigned char time_flag_i;
extern short scralim_down_s;
extern short scra_h_posit_s;
extern short scra_v_posit_s;
extern short scrb_h_posit_s;
extern short scrb_v_posit_s;
extern short scrc_h_posit_s;
extern short scrc_v_posit_s;
extern short scrz_h_posit_s;
extern short scrz_v_posit_s;
extern short waterposi_m_s;
extern unsigned char water_flag_s;
extern unsigned char waterflag_s;
extern unsigned char plring_f2_s;
extern unsigned char generate_flag;
extern unsigned char plsubchg_flag;
extern unsigned char enkeino;
extern unsigned char projector_flag;
extern unsigned char special_flag;
extern unsigned char conbine_flag;
extern unsigned char enecgflg;
extern unsigned char enecgpnt;
extern unsigned char emie3end;
extern int extrascore;
extern short demono;
extern short enddemono;
extern unsigned char mdstatus;
extern unsigned int resetflg;
extern unsigned char markerno;
extern unsigned char colrevflag;
extern unsigned char gf_flag;
extern unsigned char chibi_s;
extern unsigned char prio_s;
extern unsigned char tv_flag;
extern short edittimer;
extern short time_stop;
extern unsigned char sys_pattim;
extern unsigned char sys_patno;
extern unsigned char sys_pattim2;
extern unsigned char sys_patno2;
extern unsigned char sys_pattim3;
extern unsigned char sys_patno3;
extern unsigned char sys_pattim4;
extern unsigned char sys_patno4;
extern short sys_ringtimer;
extern short editstack;
extern short editstack2;
extern short mapcheck;
extern short blkno;
extern unsigned char edit_user;
extern unsigned char sysdirec;
extern unsigned char prio_flag;
extern unsigned char init_flag;
extern unsigned char boss_sound;
extern unsigned char shut_flag;
extern unsigned char st6clrchg;
extern unsigned char chibi_flag;
extern unsigned char mapwrt_cnt;
extern unsigned int sbufadr;
extern int stacksave;
extern short sprpage;
extern short waittimer;
extern unsigned char startcolor;
extern unsigned char colorcnt;
extern unsigned char int_flg;
extern unsigned char linkdata;
extern int cltbladr;
extern int ranum;
extern short cgwrtcnt;
extern short cgwrttim;
extern int dmastack;
extern short waterposi;
extern short waterposi_m;
extern short watermoveposi;
extern unsigned char waterspeed;
extern unsigned char water_flag;
extern unsigned char waterflag;
extern unsigned char waterflag2;
extern unsigned short bitdevadr;
extern short bitdevcnt;
extern short bitdevcnt2;
extern unsigned short hintflag;
extern short scralim_n_left;
extern short scralim_n_right;
extern short scralim_n_up;
extern short scralim_n_down;
extern short scralim_left;
extern short scralim_right;
extern short scralim_up;
extern short scralim_down;
extern short scrar_no;
extern short scra_h_keep;
extern short scra_v_keep;
extern short scra_hz;
extern short scra_vz;
extern short scra_vline;
extern unsigned char scrh_flag;
extern unsigned char scrv_flag;
extern unsigned char scra_h_count;
extern unsigned char scra_v_count;
extern unsigned char scrb_h_count;
extern unsigned char scrb_v_count;
extern unsigned char scrc_h_count;
extern unsigned char scrc_v_count;
extern unsigned char scrz_h_count;
extern unsigned char scrz_v_count;
extern unsigned char limmoveflag;
extern unsigned char playpatno1;
extern unsigned char kusya_flag;
extern short plmaxspdwk;
extern short pladdspdwk;
extern short plretspdwk;
extern unsigned char playpatno;
extern unsigned char playwrtflag;
extern short asetposi;
extern char time_item;
extern short backto_cnt;
extern unsigned char scr_cnt;
extern unsigned int demo_adr;
extern short demo_cnt;
extern short swbufcnt;
extern short scra_hline;
extern unsigned char bossflag;
extern unsigned char bossstart;
extern unsigned char loopmapno;
extern unsigned char loopmapno2;
extern unsigned char ballmapno;
extern unsigned char ballmapno2;
extern unsigned char watercoliflag;
extern unsigned char waterstop;
extern unsigned char mizuflag;
extern unsigned char sekichyuflag;
extern unsigned char plautoflag;
extern unsigned char specflag;
extern unsigned char dai2rmvflag;
extern short emyscorecnt;
extern short timebonus;
extern short ringbonus;
extern unsigned char bonus_f;
extern unsigned char edplayflag;
extern unsigned char ms_wflg;
extern game_info gKeepWork;
extern int gFadeFlag;
extern PALETTEENTRY colorwk4[64];
extern PALETTEENTRY* lpcolorwk3;
extern PALETTEENTRY colorwk2[64];
extern PALETTEENTRY* lpcolorwk;
extern unsigned char switchflag[32];
extern short_union waterdirec;
extern unsigned char clchgtim[7];
extern unsigned char clchgcnt[7];
extern ushort_union plposiwkadr;
extern unsigned char* scdadr;
extern short_union byecnt1;
extern short_union byecnt0;
extern asetz_info* asetadrz2;
extern asetz_info* asetadrz;
extern aset_info* asetadr2;
extern aset_info* asetadr;
extern short_union actset_rno;
extern char dirstk[4];
extern ushort_union scrflagz;
extern ushort_union scrflagc;
extern ushort_union scrflagb;
extern ushort_union scrflaga;
extern short_union scr_timer;
extern ushort_union scr_die;
extern short_union scroll_start;
extern ushort_union zone_flag;
extern int_union scrz_v_posit;
extern int_union scrz_h_posit;
extern int_union scrc_v_posit;
extern int_union scrc_h_posit;
extern int_union scrb_v_posit;
extern int_union scrb_h_posit;
extern int_union scra_v_posit;
extern int_union scra_h_posit;
extern unsigned int divdevwk[24];
extern unsigned char cgchgtim[6];
extern unsigned char cgchgcnt[6];
extern ushort_union pauseflag;
extern short_union intcnt;
extern short_union hintposi;
extern int_union hscroll;
extern int_union vscroll;
extern ushort_union swdata2;
extern ushort_union swdata1;
extern ushort_union swdata;
extern short_union gmmode;
extern sprite_status actwk[128];
extern int_union hscrollbuff[256];
extern short playposiwk[128];
extern sprite_statuses pbuffer[8];
extern short hscrollwork[256];
extern unsigned char flowwk[4096];
extern unsigned short blockwk[1024][4];
extern unsigned short mapwk[0x8000];
extern int linework[128];
extern short_union col_x;
extern short_union col_y;
extern ushort_union scrflagzw;
extern ushort_union scrflagcw;
extern ushort_union scrflagbw;
extern ushort_union scrflagaw;
extern int_union scrz_v_posiw;
extern int_union scrz_h_posiw;
extern int_union scrc_v_posiw;
extern int_union scrc_h_posiw;
extern int_union scrb_v_posiw;
extern int_union scrb_h_posiw;
extern int_union scra_v_posiw;
extern int_union scra_h_posiw;
extern int_union systemtimer;
extern short_union editmode;
extern short_union editno;
extern unsigned char flowercnt[3];
extern int_union flowerposi[192];
extern short_union debugflag;
extern short_union demoflag;
extern uint_union debugwork;
extern int_union pltime;
extern short_union stageno;
extern short_union stageno_i;
extern short_union gametimer;
extern short_union gameflag;
extern unsigned char flagwork[766];
extern unsigned short sm_adr0[16384];
extern int tv_adr[224];
