short fcol(sprite_status* pActwk);
short fcol_d(sprite_status* pActwk);
short fcol_r(sprite_status* pActwk);
short fcol_u(sprite_status* pActwk);
short fcol_l(sprite_status* pActwk);
short scdend(sprite_status* pActwk, short iXposi, short iYposi, short iOffset, short iBlkMsk, short iRideon, char* cpDirStk);
short scdchk(sprite_status* pActwk, short iXposi, short iYposi, short iOffset, short iBlkMsk, short iRideon, char* cpDirStk);
short scdchk2(sprite_status* pActwk, short iXposi, short iYposi, short iOffset, short iBlkMsk, short iRideon, char* cpDirStk);
short scdend_r(sprite_status* pActwk, short iXposi, short iYposi, short iOffset, short iBlkMsk, short iRideon, char* cpDirstk);
short scdchk_r(sprite_status* pActwk, short iXposi, short iYposi, short iOffset, short iBlkMsk, short iRideon, char* cpDirstk);
short scdchk2_r(sprite_status* pActwk, short iXposi, short iYposi, short iBlkMsk, short iRideon, char* cpDirstk);
short scramapad(sprite_status* pActwk, short iXposi, short iYposi);
short dirchk(sprite_status* pActwk, short scd0, short scd1);
short scdcnv(void);
short st_elseDataChk(short iBlkNo, sprite_status* pActwk);
short st_wackyDataChk(short iBlkNo, sprite_status* pActwk);
short st_starDataChk(short iBlkNo, sprite_status* pActwk);
short st_metalDataChk(short iBlkNo, sprite_status* pActwk);
unsigned char CCset(int lSrc, int lDst);
unsigned char CSset(unsigned short wSrc, unsigned short wDst);
unsigned char bchg(unsigned char bySrc, unsigned char byDst);
