void gene(sprite_status* pActwk);
void gene_init(sprite_status* pActwk);
void gene_move0(sprite_status* pActwk);
void gene_move1(sprite_status* pActwk);
void kira_set(sprite_status* pActwk);
void kira_move(sprite_status* pActwk);
short gene_coli(sprite_status* pActwk, sprite_status* pPlaywk);
void bring2(sprite_status* pActwk);
void bring2init(sprite_status* pActwk);
void bring2move0(sprite_status* pActwk);
void bring2move1(sprite_status* pActwk);
void bigring(sprite_status* pActwk);
void bring_init(sprite_status* pActwk);
void bring_move0(sprite_status* pActwk);
void bring_move1(sprite_status* pActwk);
short bring_coli(sprite_status* pActwk, sprite_status* pPlaywk);
void mosugu(sprite_status* pActwk);
void mosug_init(sprite_status* pActwk, sprite_status* pPlaywk);
void mosug_move0(sprite_status* pActwk, sprite_status* pPlaywk);
void mosug_move1(sprite_status* pActwk, sprite_status* pPlaywk);
void offset_set(sprite_status* pActwk);
void goal(sprite_status* pActwk);
void goal_init(sprite_status* pActwk);
void goal_move0(sprite_status* pActwk);
void goal_move1(sprite_status* pActwk);
void goal_move2(sprite_status* pActwk);
void goal_move3(sprite_status* pActwk);
void genecolor(void);
