void bye_chk(void);
void play00(sprite_status* actionwk);
void muteki_set(void);
void test_mapwrt(void);
void play00init(void);
void mizuki_set(void);
unsigned int mapno_chk(short d2, short d3);
void scr_h(void);
void play00move(void);
void playpowercnt(void);
void playposiwkset(void);
void plwaterchk(void);
void playsave(void);
void backto_chk(void);
void play00walk(void);
void play00jump(void);
void ball00walk(void);
void ball00jump(void);
void buramove(void);
void kuru2move(void);
void chk11(void);
void levermove(void);
void lmovecol(void);
void plwalk_l(void);
void plwalk_r(void);
void balllmove(void);
void ballwalk_l(void);
void ballwalk_r(void);
void jumpmove(void);
void hedcolchk(void);
void limitchk(void);
void ballchk(void);
void ballset(void);
unsigned char jumpchk(void);
void jumpchk2(void);
void keispd(void);
void keispd2(void);
void fallchk(void);
void direcchg(void);
void jumpcolchk(void);
void jumpcolsub(void);
void jumpcolsub0(void);
void play00damage(void);
void play00damage_sub(void);
void play00die(void);
void play00die_sub(void);
void play00erase(void);
void loopchk(void);
void st7_x(void);
void patchgmain(void);
void patchgmain2(unsigned char* pat_pointer);
void playrunchg(unsigned char pat_no);
void playrunchg2(unsigned char pat_no);
void playrunchg3(unsigned char pat_no);
void playetc_chg(void);
void little_runchg(void);
char little_patchg(char pat_index);
void playwrt(void);
unsigned char frip_spd(int* cal_jump, unsigned char* cal_direc);
