short ride_on_clr(sprite_status* pActwk, sprite_status* pPlayerwk);
short ride_on_set(sprite_status* pActwk, sprite_status* pPlayerwk);
short hitchk_u(sprite_status* pActwk, sprite_status* pPlayerwk);
short ridechk(sprite_status* pActwk, sprite_status* pPlayerwk);
short ride_on_chk(sprite_status* pActwk, sprite_status* pPlayerwk);
short hitchk(sprite_status* pActwk, sprite_status* pPlayerwk);
short hit_v(sprite_status* pActwk, sprite_status* pPlayerwk, short iHitXs, short iHitHs);
short hit_x(sprite_status* pActwk, sprite_status* pPlayerwk, short iHitXs, short iD5);
short push_set(sprite_status* pActwk, sprite_status* pPlayerwk);
short push_clr(sprite_status* pActwk, sprite_status* pPlayerwk);
short hit_y(sprite_status* pActwk, sprite_status* pPlayerwk, short iHitYs);
short hit_yu(sprite_status* pActwk, sprite_status* pPlayerwk, short iHitYs);
short hit_yu1(sprite_status* pActwk, sprite_status* pPlayerwk, short iHitYs);
short hit_yu0(sprite_status* pActwk, sprite_status* pPlayerwk, short iHitYs);
short hit_e(sprite_status* pActwk, sprite_status* pPlayerwk);
void side_coli(sprite_status* pActwk, sprite_status* pPlayerwk);
void hit_set(sprite_status* pActwk, sprite_status* pPlayerwk);
void hit_clr(sprite_status* pActwk, sprite_status* pPlayerwk);
