void ring(sprite_status* pActwk);
void ringinit(sprite_status* pActwk);
void ringmove(sprite_status* pActwk);
void ringget(sprite_status* pActwk);
void ringgetsub(void);
void ringdie(sprite_status* pActwk);
void ringerase(sprite_status* pActwk);
void flyring(sprite_status* pActwk);
void flyringinit(sprite_status* pActwk);
void flyringmove(sprite_status* pActwk);
void flyringget(sprite_status* pActwk);
void flyringdie(sprite_status* pActwk);
void flyringerase(sprite_status* pActwk);
