extern int overint;
extern short gmtime1;
extern short gmtime0;
extern short intmode;
extern unsigned short comdata_s7;
extern unsigned short comdata_s6;
extern unsigned short comdata_s5;
extern unsigned short comdata_s4;
extern unsigned short comdata_s3;
extern unsigned short comdata_s2;
extern unsigned short comdata_s1;
extern unsigned short comdata_s0;
extern unsigned short comdata_m7;
extern unsigned short comdata_m6;
extern unsigned short comdata_m5;
extern unsigned short comdata_m4;
extern unsigned short comdata_m3;
extern unsigned short comdata_m2;
extern unsigned short comdata_m1;
extern unsigned short comdata_m0;
extern unsigned char comflag_s;
extern unsigned char comflag_m;
extern short sr_save;
extern unsigned char colorflg;
extern unsigned char push_flg;
extern short actset_tm[8];
extern short colorno;
extern short coltimer;
extern int ProcMode;
extern int DLLRetMode;
