int overint;
short gmtime1;
short gmtime0;
short intmode;
unsigned short comdata_s7;
unsigned short comdata_s6;
unsigned short comdata_s5;
unsigned short comdata_s4;
unsigned short comdata_s3;
unsigned short comdata_s2;
unsigned short comdata_s1;
unsigned short comdata_s0;
unsigned short comdata_m7;
unsigned short comdata_m6;
unsigned short comdata_m5;
unsigned short comdata_m4;
unsigned short comdata_m3;
unsigned short comdata_m2;
unsigned short comdata_m1;
unsigned short comdata_m0;
unsigned char comflag_s;
unsigned char comflag_m;
short sr_save;
unsigned char colorflg;
unsigned char push_flg;
short actset_tm[8];
short colorno;
short coltimer;
int ProcMode;
int DLLRetMode;
