void specaction(void);
void actmain(sprite_status_sp* work);
void zbuf_init(void);
void zbuf_set(sprite_status_sp* work, int length);
void zbuf_patset(void);
void zpatset(short z_buffer_start);
short zpatset_call(short z_buffer_number);
void patinit(sprite_status_sp* work, unsigned char pattbl_number);
void patinit1(sprite_status_sp* work, unsigned char pattbl_number);
void specpatset(sprite_status_sp* work);
void n_patset(sprite_status_sp* work, sprite_pattern* sprpat_adr);
