extern unsigned short gdemoflg;
extern unsigned short pl_yspd;
extern unsigned short pl_xspd;
extern unsigned char gameinit;
extern unsigned char ufoleftsave;
extern unsigned char good_flag;
extern unsigned char endskipflg;
extern unsigned char white_inflg;
extern unsigned char stagenm_save;
extern unsigned char nobramflg;
extern unsigned char modeflg;
extern unsigned char goodflg;
extern unsigned char clrstnm_sp;
extern unsigned char clrstnm;
extern unsigned short reg1save;
extern unsigned short rcnt;
extern int timesave;
extern unsigned char stage_no;
extern unsigned char round_no;
extern unsigned char ufoleft;
extern unsigned char clrspflg;
extern int_union spe_time;
extern unsigned short ringno;
extern unsigned char stagenm;
extern unsigned char spgmmode;
extern unsigned char clrspflg_m;
extern unsigned char stagenm_m;
extern int slidewk[1024];
extern int* ib_adr;
extern int* sg_adr;
