void SetUseOk(short unknown1, short unknown2, short unknown3);
void m2mainchk(void);
void m2subset(void);
int specgame(void);
int ufochk(void);
void game_clear(void);
void game_over(void);
void specgame_init(void);
void disp(void);
int disp_main(void);
void gsc_up20(void);
void gsc_up(int lScore);
short pause_chk(void);
void map_init(void);
void bwrtset(unsigned int tblno4);
void stone_color_set(void);
void panel_box(void);
void colset(PALETTEENTRY* lpPeSrc);
void sinit0(void);
void sinit1(void);
void sinit2(void);
void sinit3(void);
void sinit4(void);
void sinit5(void);
void sinit6(void);
void sinit7(void);
void stage_init(void);
void key_set(short ReqNo);
void hscal_1(void);
void hscal_2(void);
void hscal0_0(void);
void hscal1_0(void);
void hscal2_0(void);
void hscal0(short* a0, short* a1, int d0, int d1, short d3, short d4, short d7);
void hscal0_4(void);
void hscal1_4(void);
void hscal2_4(void);
void hscal4(short* a0, short* a1, int* a2, short d0, short d7);
void hscal0_5(void);
void hscal1_5(void);
void hscal2_5(void);
void hscal5(short* a0, char* a2, short d0, short d2, short d7);
void rlspd_get(int* d0, int* d1);
void hscrspd_get(int* lD0, int* lD1);
void hscrl0(void);
void hscrl1(void);
void hscrl2(void);
void hscrl3(void);
void hscrl4(void);
void hscrl5(void);
void hscrl6(void);
void hscrl7(void);
void hscal(void);
void colchg0(void);
void colchg1(void);
void colchg2(void);
void colchg3(void);
void colchg4(void);
void colchg5(void);
void colchg6(void);
void colchg7(void);
void color_change(void);
