void specplayer(sprite_status_sp* plwk);
void init_xyget(sprite_status_sp* plwk);
void clear_chk(void);
void colli_evt(sprite_status_sp* plwk);
void noevt(sprite_status_sp* plwk);
void evt08(sprite_status_sp* plwk);
void evt01(sprite_status_sp* plwk);
void evt02(sprite_status_sp* plwk);
void evt03(sprite_status_sp* plwk);
void evt04(sprite_status_sp* plwk);
void evt05(sprite_status_sp* plwk);
void evt06(sprite_status_sp* plwk);
void tobi_b0(sprite_status_sp* plwk);
void tobi_b2(sprite_status_sp* plwk);
void tobi_b4(sprite_status_sp* plwk);
void tobi_b6(sprite_status_sp* plwk);
void tobi_b(sprite_status_sp* plwk, short cal_x, short cal_y);
void evt07(sprite_status_sp* plwk);
void tobi_s0(sprite_status_sp* plwk);
void tobi_s2(sprite_status_sp* plwk);
void tobi_s4(sprite_status_sp* plwk);
void tobi_s6(sprite_status_sp* plwk);
void tobi_s(sprite_status_sp* plwk, short cal_x, short cal_y);
void boundchk(sprite_status_sp* plwk);
short k_search(sprite_status_sp** new_actwk);
void jumpset(sprite_status_sp* plwk);
void rlmove(sprite_status_sp* plwk);
void rlmove_j(sprite_status_sp* plwk);
void speed_ud(sprite_status_sp* plwk);
void go_down(sprite_status_sp* plwk);
void go_up(sprite_status_sp* plwk);
void go_right(sprite_status_sp* plwk);
void go_left(sprite_status_sp* plwk);
void go_x_plus(sprite_status_sp* plwk, unsigned short cal_plus, short cal_speed);
void ptrlget(sprite_status_sp* plwk);
void plptsel(sprite_status_sp* plwk);
void plcgchg(sprite_status_sp* plwk);
void specsibuki(sprite_status_sp* sibukiwk);
void sibuki0(sprite_status_sp* sibukiwk);
void sibuki1(sprite_status_sp* sibukiwk);
void sibuki2(sprite_status_sp* sibukiwk);
void sibuki_clr(void);
void kemuri(sprite_status_sp* kemuriwk);
void kemuri0(sprite_status_sp* kemuriwk);
void kemuri1(sprite_status_sp* kemuriwk);
void time_stone(sprite_status_sp* stonewk);
void t_stone0(sprite_status_sp* stonewk);
void t_stone1(sprite_status_sp* stonewk);
void t_stone2(sprite_status_sp* stonewk);
void t_stone3(sprite_status_sp* stonewk);
void tskira0(sprite_status_sp* kirawk);
void tskira00(sprite_status_sp* kirawk);
void tskira01(sprite_status_sp* kirawk);
void tskira1(sprite_status_sp* kirawk);
void tskira10(sprite_status_sp* kirawk);
void tskira11(sprite_status_sp* kirawk);
