extern unsigned char* demoadr;
extern int hsdata5;
extern int hsdata4;
extern int hsdata3;
extern int hsdata2;
extern int hsdata1;
extern int hsdata0;
extern unsigned short sonicup_no;
extern unsigned char spgmmode_tmp;
extern unsigned char clfflg;
extern unsigned char demoflg;
extern unsigned char pauseflg;
extern PALETTEENTRY colorsave[64];
extern unsigned char demowk[4096];
extern unsigned short dummy100[128];
extern unsigned short dummy000[128];
extern unsigned int hdatabuf_l[128];
extern unsigned int* hdatabuf;
extern unsigned short mpopenwk[1024];
extern unsigned char rlscrflg_save;
