#include "../TYPES.h"

unsigned char plcgwk[1024];
unsigned char rlscrflg;
unsigned char cgchgflg;
uint_union se_no;
unsigned char sprbuf[640];
zoom_info zoomwk;
short hane_cnt;
short damage_cnt;
short chg_timer;
unsigned short hane_nm;
hane_info* hane_adr;
unsigned short damage_nm;
damage_info* damage_adr;
unsigned char pmflag;
ushort_union swdata_pl;
short jmpswcnt;
short rufo_getnm;
unsigned char game_start;
unsigned char tcnt20;
unsigned char tdecflg;
unsigned char gmclrflg;
unsigned char pldeadflg;
unsigned char* colliadr;
short bpsave_y;
short bpsave_x;
unsigned char demoend;
unsigned char tv_save[768];
unsigned short z_buffer[512];
sprite_status_sp specactwk[48];
