extern unsigned char plcgwk[1024];
extern unsigned char rlscrflg;
extern unsigned char cgchgflg;
extern uint_union se_no;
extern unsigned char sprbuf[640];
extern zoom_info zoomwk;
extern short hane_cnt;
extern short damage_cnt;
extern short chg_timer;
extern unsigned short hane_nm;
extern hane_info* hane_adr;
extern unsigned short damage_nm;
extern damage_info* damage_adr;
extern unsigned char pmflag;
extern ushort_union swdata_pl;
extern short jmpswcnt;
extern short rufo_getnm;
extern unsigned char game_start;
extern unsigned char tcnt20;
extern unsigned char tdecflg;
extern unsigned char gmclrflg;
extern unsigned char pldeadflg;
extern unsigned char* colliadr;
extern short bpsave_y;
extern short bpsave_x;
extern unsigned char demoend;
extern unsigned char tv_save[768];
extern unsigned short z_buffer[512];
extern sprite_status_sp specactwk[48];
