void batta(sprite_status* pActwk);
void batta_init(sprite_status* pActwk);
short emylr_jump(sprite_status* pActwk, unsigned char byD3);
void batta_down(sprite_status* pActwk);
void batta_floor(sprite_status* pActwk);
void batta_wait(sprite_status* pActwk);
void batta_up(sprite_status* pActwk);
void batta_ceiling(sprite_status* pActwk);
void batta_fall(sprite_status* pActwk);
void batta_wall(sprite_status* pActwk);
void batta_patexg(sprite_status* pActwk);
