void beem6(sprite_status* actionwk);
void beem6_init(sprite_status* actionwk);
void beem6_wait(sprite_status* actionwk);
void cntdwn(sprite_status* actionwk);
void beem6_move(sprite_status* actionwk);
void beem6_posiset(sprite_status* actionwk);
void beem6_actsch(void);
void clrset0(void);
void clrset0_2(void);
void clrset1(sprite_status* actionwk, char d0);
void maeclrset(sprite_status* actionwk, char d0);
