void egg6boss(sprite_status* pActwk);
void egg6_hitchk(sprite_status* pActwk);
void egg6_coliset(sprite_status* pActwk);
void egg6_beam_ctrl(void);
void egg6_start(sprite_status* pActwk);
void egg6_ini(sprite_status* pActwk);
void egg6_none(sprite_status* pActwk);
void egg6_down(sprite_status* pActwk);
void egg6_hover(sprite_status* pActwk);
void fuwafuwa(sprite_status* pActwk);
void egg6_up(sprite_status* pActwk);
void egg6_event(sprite_status* pActwk);
void beamdemo_start(sprite_status* pActwk);
void beam_start(sprite_status* pActwk);
void rakkabutu(sprite_status* pActwk);
void event_end(sprite_status* pActwk);
void egg6_event_retry(sprite_status* pActwk);
void egg6_dead1(sprite_status* pActwk);
void egg6_dead2(sprite_status* pActwk);
void enkei_in(sprite_status* pActwk);
void enkei_out(sprite_status* pActwk);
void egg6_flashout(void);
void egg6_flashin(void);
void egg6_cgchg(sprite_status* pActwk);
void dead2_end(sprite_status* pActwk);
void door_open(sprite_status* pActwk);
void egg6_dead3(sprite_status* pActwk);
void egg6_dead4(sprite_status* pActwk);
void genecolor_setchk(sprite_status* pActwk);
void dead_snc_pos2(void);
void dead_snc_pos(void);
void egg6meca0(sprite_status* pActwk);
void egg6meca0_ini(sprite_status* pActwk);
void egg6meca0_01(sprite_status* pActwk);
void egg6meca0_02(sprite_status* pActwk);
void egg6meca1(sprite_status* pActwk);
void egg6meca1_ini(sprite_status* pActwk);
void egg6meca1_01(sprite_status* pActwk);
void egg6meca2(sprite_status* pActwk);
void egg6meca2_ini(sprite_status* pActwk);
void egg6meca2_01(sprite_status* pActwk);
void egg6bakuha(sprite_status* pActwk);
void egg6bakuha_ini(sprite_status* pActwk);
void egg6bakuha_01(sprite_status* pActwk);
void egg6bakuha_02(sprite_status* pActwk);
void egg6toge(sprite_status* pActwk);
void egg6toge_ini(sprite_status* pActwk);
void egg6toge_01(sprite_status* pActwk);
void egg6toge_02(sprite_status* pActwk);
void egg6gareki(sprite_status* pActwk);
void egg6gareki_ini(sprite_status* pActwk);
void egg6gareki_01(sprite_status* pActwk);
void egg6gareki_02(sprite_status* pActwk);
void egg6beam(sprite_status* pActwk);
void egg6beam_ini(sprite_status* pActwk);
void egg6beam_01(sprite_status* pActwk);
void egg6yuka(sprite_status* pActwk);
void egg6yuka_ini(sprite_status* pActwk);
void egg6yuka_01(sprite_status* pActwk);
void egg6yuka_02(sprite_status* pActwk);
void egg6_yuka_ridechk(sprite_status* pActwk);
void egg6_yuka_ride_on(sprite_status* pActwk);
short egg6_yuka_hasami_chk(sprite_status* pActwk);
short mydamage(sprite_status* pActwk);
void egg6door(sprite_status* pActwk);
void egg6door_ini(sprite_status* pActwk);
void egg6door_closewait(sprite_status* pActwk);
void egg6door_move(sprite_status* pActwk);
void egg6door_closed(sprite_status* pActwk);
void egg6door_openwait(sprite_status* pActwk);
void egg6door_beamer(sprite_status* pActwk);
short act_search(unsigned char wActNo, unsigned char* bpActoff, sprite_status** ppActAdr);
short get_gareki_y(sprite_status* pActwk);
void make_toge(sprite_status* pActwk, short iD0);
void make_yuka(sprite_status* pActwk, short iD0);
void make_gareki(sprite_status* pActwk, short iD0);
void make_gareki4(sprite_status* pActwk);
void make_beam(short iD0);
void make_bakuha(sprite_status* pActwk);
void make_bakuha2(sprite_status* pActwk);
void make_meca(sprite_status* pActwk);
void frameout_chk(sprite_status* pActwk);
short get_snc_floor(void);
short get_beam_pos(void);
void egg6_jisin(sprite_status* pActwk);
void colchg_set(unsigned char byD0);
void colchg_stop(void);
void colchg_start(void);
