void tobira(sprite_status* actionwk);
void master(sprite_status* actionwk);
void m_init(sprite_status* actionwk);
void ini_com(sprite_status* actionwk, sprite_status* a1, short* d0, short* d1);
void m_closed(sprite_status* actionwk);
void ms_end(sprite_status* actionwk);
void m_open(sprite_status* actionwk);
void m_opend(sprite_status* actionwk);
void m_close(sprite_status* actionwk);
short ms_hitchk(sprite_status* actionwk);
short m_area(sprite_status* actionwk, short d4, short d5);
