short colli_pl_sikake_d(sprite_status* pActwk, sprite_status* pPlayerwk, short collinum);
short colli_pl_sikake(sprite_status* pActwk, sprite_status* pPlayerwk, short collnum);
void tobita1(sprite_status* pActwk);
void tobita_init(sprite_status* pActwk);
void tobita_stop_r(sprite_status* pActwk);
void tobita_stop_l(sprite_status* pActwk);
void tobita_ride_r(sprite_status* pActwk);
void tobita_ride_l(sprite_status* pActwk);
void tobita_yure_r(sprite_status* pActwk);
void tobita_yure_l(sprite_status* pActwk);
void hariyama(sprite_status* pActwk);
void hari_init(sprite_status* pActwk);
void hari_normal(sprite_status* pActwk);
