void ene_kama(sprite_status* pActwk);
void kama_init(sprite_status* pActwk);
void kama_disp(sprite_status* pActwk);
void kama_fall(sprite_status* pActwk);
void kama_wait(sprite_status* pActwk);
void kama_atck(sprite_status* pActwk);
void kama_pati(sprite_status* pActwk);
void kama_move(sprite_status* pActwk);
void kama_reve(sprite_status* pActwk);
void movement(sprite_status* pActwk);
void set_wpkama(sprite_status* pActwk);
void tama_kama(sprite_status* pActwk);
void wpkama_init(sprite_status* pActwk);
void wpkama_wait(sprite_status* pActwk);
void wpkama_move(sprite_status* pActwk);
void wpkama_disp(sprite_status* pActwk);
short wpkama_colicheck(sprite_status* pActwk, sprite_status* pPlaywk);
void wpkama_reve(sprite_status* pActwk, sprite_status* pPlaywk);
