unsigned char CSset_b(unsigned char bySrc, unsigned char byDst);
void mecasnc3(sprite_status* pActwk);
void mecasnc3_init(sprite_status* pActwk);
void mecasnc3_matu1(sprite_status* pActwk);
void mecasnc3_come(sprite_status* pActwk);
void mecasnc3_hovr(sprite_status* pActwk);
void yposisetsub(sprite_status* pActwk);
void mecasnc3_upmv(sprite_status* pActwk);
void setfire(sprite_status* pActwk);
void mecasnc3_rght(sprite_status* pActwk);
void mecasnc3_fout(sprite_status* pActwk);
void emie_speedset(sprite_status* pActwk);
void emie_speedsety(sprite_status* pActwk);
void emie_speedsetx(sprite_status* pActwk);
void emie3(sprite_status* pActwk);
void emie3_init(sprite_status* pActwk);
void emiewalkret(sprite_status* pActwk);
void emie3_walk(sprite_status* pActwk);
void emie3_help(sprite_status* pActwk);
void setdirect(sprite_status* pActwk, sprite_status* pPlaywk);
void dir_right(sprite_status* pActwk);
void dir_left(sprite_status* pActwk);
void empatchg(sprite_status* pActwk, unsigned char** bppPtbl);
void emie3clrsetx(PALETTEENTRY* pPalet);
void emie3clrset(void);
void heartset(sprite_status* pActwk);
void hari3x_fout(sprite_status* pActwk);
void hari3x(sprite_status* pActwk);
void hari3x_ridechk(sprite_status* pActwk);
void hari3x_init(sprite_status* pActwk);
void hari3x_move(sprite_status* pActwk);
void brknset(sprite_status* pActwk);
void hari3x_spdset(sprite_status* pActwk);
void hari3x_brkn(sprite_status* pActwk);
void heart3(sprite_status* pActwk);
void heart3_init(sprite_status* pActwk);
void heart3_move(sprite_status* pActwk);
void msnc3fire(sprite_status* pActwk);
void msnc3fire_init(sprite_status* pActwk);
void msnc3fire_move(sprite_status* pActwk);
