void pocket(sprite_status* actionwk);
void pocket0(sprite_status* actionwk);
void a_move0(sprite_status* actionwk);
void a_check(sprite_status* actionwk, sprite_status* a6);
void to_a_move1(sprite_status* actionwk);
void a_move00(sprite_status* actionwk);
void a_move1(sprite_status* actionwk);
void a_move2(sprite_status* actionwk);
void a_move3(sprite_status* actionwk);
void a_move4(sprite_status* actionwk);
void a_move5(sprite_status* actionwk);
void a_move6(sprite_status* actionwk);
void a_move7(sprite_status* actionwk);
void a_move8(sprite_status* actionwk);
void pocket1(sprite_status* actionwk);
void b_move(sprite_status* actionwk);
void b_die(sprite_status* actionwk);
