name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        install: base-devel mingw-w64-i686-gcc mingw-w64-i686-SDL2

    - uses: actions/checkout@v4
    
    - name: Build
      run: make
